name: Commit Stage Workflow

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  checks: write

jobs:
  commit-stage:
    name: Commit Stage Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out pr branch
        uses: actions/checkout@v3
        with:
          path: revision
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: base
      - name: View working folder
        run:  tree -a -I '.git'      
      - name: Structured diff of what has changed
        uses: Tufin/oasdiff-action@v2
        with:
          base: 'base/api-definitions/product-catalog.oas.yaml'
          revision: 'revision/api-definitions/product-catalog.oas.yaml'
          format: 'yaml'
      - name: Install Spectral OWASP ruleset 
        run:  npm install --save-dev @stoplight/spectral-owasp-ruleset      
      - name: Install spectral
        run: npm list -g @stoplight/spectral-cli || npm install -g @stoplight/spectral-cli
      - name: Lint API definitions
        run: spectral lint --ruleset revision/.spectral.yaml revision/api-definitions/**/*.oas.yaml
      - name: Breaking change check
        uses: Tufin/oasdiff-action@v2
        with:
          base: 'base/api-definitions/product-catalog.oas.yaml'
          revision: 'revision/api-definitions/product-catalog.oas.yaml'
          format: 'yaml'
          breaking-only: true
          fail-on-diff: true
      